services:
  - type: web
    name: zeiterfassung-brandnertal
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_PATH
        value: /opt/render/project/src/data.db
      - key: NODE_ENV
        value: production
